export const blockReward = {
  "BTC": {
    dailyReward: 20000,
    timePerBlock: 600,
    name: "BITCOIN",
    ticker: "BTC",
    icon: "btc.svg",
    coinGeckoId: "bitcoin",
  },
  "DOGE": {
    dailyReward: 44,
    timePerBlock: 600,
    name: "DOGECOIN",
    ticker: "DOGE",
    icon: "doge.svg",
    coinGeckoId: "dogecoin",
  },
  "ETH": {
    dailyReward: 0.0044,
    timePerBlock: 600,
    name: "ETHEREUM",
    ticker: "ETH",
    icon: "eth.svg",
    coinGeckoId: "ethereum",
  },
  "BNB": {
    dailyReward: 0.035,
    timePerBlock: 600,
    name: "BINANCECOIN",
    ticker: "BNB",
    icon: "bnb.svg",
    coinGeckoId: "binancecoin",
  },
  "MATIC": {
    dailyReward: 35,
    timePerBlock: 600,
    name: "POLYGON",
    ticker: "matic-network",
    icon: "matic.svg",
    coinGeckoId: "matic-network",
  },
  "RLT": {
    dailyReward: 30,
    timePerBlock: 600,
    name: "ROLLERTOKEN",
    ticker: "RLT",
    icon: "rlt.svg",
  },
  "SOL": {
    dailyReward: 0.11,
    timePerBlock: 600,
    name: "SOLANA",
    ticker: "SOL",
    icon: "sol.svg",
    coinGeckoId: "solana",
  },
  "RST": {
    dailyReward: 250,
    timePerBlock: 600,
    name: "ROLLERSEZON",
    icon: "rst.svg",
  },
  "TRX": {
    dailyReward: 75,
    timePerBlock: 600,
    name: "TRON",
    ticker: "tron",
    icon: "trx.svg",
    coinGeckoId: "tron",
  },
  "LTC": {
    dailyReward: 0.3,
    timePerBlock: 600,
    name: "LITECOIN",
    ticker: "ltc",
    icon: "ltc.svg",
    coinGeckoId: "litecoin",
  },
}
