export const blockReward = {
  "BTC": {
    dailyReward: 20000,
    timePerBlock: 600,
    name: "BITCOIN",
    ticker: "BTC",
    icon: "btc.svg",
    coinGeckoId: "bitcoin",
  },
  "DOGE": {
    dailyReward: 94,
    timePerBlock: 600,
    name: "DOGECOIN",
    ticker: "DOGE",
    icon: "doge.svg",
    coinGeckoId: "dogecoin",
  },
  "ETH": {
    dailyReward: 0.007,
    timePerBlock: 600,
    name: "ETHEREUM",
    ticker: "ETH",
    icon: "eth.svg",
    coinGeckoId: "ethereum",
  },
  "BNB": {
    dailyReward: 0.029,
    timePerBlock: 600,
    name: "BINANCECOIN",
    ticker: "BNB",
    icon: "bnb.svg",
    coinGeckoId: "binancecoin",
  },
  "MATIC": {
    dailyReward: 55,
    timePerBlock: 600,
    name: "POLYGON",
    ticker: "POL",
    icon: "matic.svg",
    coinGeckoId: "matic-network",
  },
  "RLT": {
    dailyReward: 30,
    timePerBlock: 600,
    name: "ROLLERTOKEN",
    ticker: "RLT",
    icon: "rlt.svg",
  },
  "SOL": {
    dailyReward: 0.12,
    timePerBlock: 600,
    name: "SOLANA",
    ticker: "SOL",
    icon: "sol.svg",
    coinGeckoId: "solana",
  },
  "RST": {
    dailyReward: 250,
    timePerBlock: 600,
    name: "ROLLERSEZON",
	ticker: "RST",
    icon: "rst.svg",
  },
  "TRX": {
    dailyReward: 70,
    timePerBlock: 600,
    name: "TRON",
    ticker: "TRX",
    icon: "trx.svg",
    coinGeckoId: "tron",
  },
  "LTC": {
    dailyReward: 0.15,
    timePerBlock: 600,
    name: "LITECOIN",
    ticker: "LTC",
    icon: "ltc.svg",
    coinGeckoId: "litecoin",
  },
  "XRP": {
    dailyReward: 5,
    timePerBlock: 600,
    name: "RIPPLE",
    ticker: "XRP",
    icon: "xrp.svg",
    coinGeckoId: "ripple",
  },
}
